dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - npm install -g @angular/compiler-cli
  - cd front-end/OSGB
  - yarn install
  - yarn test
script: yarn run test
notifications:
    slack: aerotivelabs:wnHT2hFn1UgSUgViiBdLiga7#rgix-ci