dist: trusty
sudo: required
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - cd front-end
  - npm install -g webpack
  - npm install -g gulp-cli

script: yarn start 